project:
  type: website
  resources:
    - "pdf/*.pdf"
  
website:
  title: "Home"
  site-url: https://mroberts1.github.io/digital-culture-sp24/
  twitter-card:
    creator: "@mroberts_vma"
    card-style: summary_large_image
  favicon: "/img/cropped-cropped-flourish-1-270x270.gif"
  margin-header: |
    ![](/img/CollegeLockupStacked.jpg){size="50%"}
  navbar:
    background: "#62259d"
    search: true
    left:
      - text: Syllabus
        file: syllabus.qmd
      - text: Bibliography
        file: bibliography.qmd
      - text: ChatGPT syllabus
        file: chatgpt-syllabus.qmd
    right:
      - icon: envelope
        aria-label: envelope
        href: mailto:martin_roberts@emerson.edu
      - icon: mastodon
        aria-label: mastodon
        href: https://merveilles.town/@dokoissho
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1
      - icon: facebook
        aria-label: facebook
        href: https://facebook.com/mr05301
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/mroberts_VMA
format: 
  html:
    toc: false
    toc-depth: 3  
    toc-location: right
    toc-title: '   '
    theme: 
      light: ember.scss
      dark: slate
    css: custom.scss
    fontsize: 1.1em
    linestretch: 1.5
    smooth-scroll: true
    linkcolor: "#62259d"
    page-layout: article
    title-block-banner: true
fig-responsive: true
image-alt: " "
execute:
  echo: false
editor: source
